<script src="assets/js/vendor/bootstrap.min.js"></script>
<script src="assets/js/vendor/fontawesome.js"></script>
<script src="assets/js/vendor/aos.js"></script>
<script src="assets/js/vendor/jquery.appear.js"></script>
<script src="assets/js/vendor/jquery.odometer.min.js"></script>
<script src="assets/js/vendor/sidebar.js"></script>
<script src="assets/js/vendor/magnific-popup.js"></script>
<script src="assets/js/vendor/gsap.min.js"></script>
<script src="assets/js/vendor/ScrollTrigger.min.js"></script>
<script src="assets/js/vendor/Splitetext.js"></script>
<script src="assets/js/vendor/mobilemenu.js"></script>
<script src="assets/js/vendor/owlcarousel.min.js"></script>
<script src="assets/js/vendor/nice-select.js"></script>
<script src="assets/js/vendor/waypoints.js"></script>
<script src="assets/js/vendor/slick-slider.js"></script>
<script src="assets/js/vendor/circle-progress.js"></script>
<script src="assets/js/main.js?v=55234"></script>